// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgcmhwbwefeqpnrxnwuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnY21od2J3ZWZlcXBucnhud3VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMzU0MjgsImV4cCI6MjA2MTkxMTQyOH0.3IOJR5fSUHrfecj4iTTjOoRW4usT9lE7CnknuPGfk6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);